package ar.com.utn.controllers;

import ar.com.utn.models.Usuario;
import ar.com.utn.repositories.UsuarioRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

/**
 * Created by julis on 17/5/2017.
 */
@Controller
@RequestMapping(path="/demo")
public class UsuarioController {

    @Autowired // This means to get the bean called userRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    private UsuarioRepository usuarioRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Usuario n = new Usuario();
        n.setName(name);
        n.setEmail(email);
        usuarioRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody List<Usuario> getAllUsers() {
        // This returns a JSON or XML with the users
        return (List<Usuario>) usuarioRepository.findAll();
    }
}
