package ar.com.utn.mercadopago;

import ar.com.utn.mercadopago.model.UserMP;
import ar.com.utn.models.Usuario;

/**
 * Created by julian on 12/10/17.
 */
public interface MercadoPagoApi {

    /**
     * if the payment is approved, then return the id of the payment
     * generated by MP
     * @param paymentMP
     * @return
     * @throws Exception
     */
//    String makePayment(PaymentMP paymentMP) throws Exception;


//
//    AdditionalInfoMP buildAdditionalInfoMP(OrderCustomer orderCustomer);
//
//    PaymentMP buildPaymentMP(double amount, String tokenMP, String title, int installments, String paymentMethodId,
//                             UserMP userMP, AdditionalInfoMP additionalInfoMP, double commission);

    void setAccessToken(String accessToken);


    UserMP buildUserMP(Usuario user);

}
